### ISSUE TITLE
evaluating 'tileDef.url'

### ISSUE THREAD

**Issue by trakais** [mattiasb/Leaflet.MultiTileLayer#1]
Hi! 

I tried to implement this plugin, with little changes to example code, but when I zoom in past the defined zoom level, I get this: "'undefined' is not an object (evaluating 'tileDef.url'"). Layers switch fine in zoom levels from 0-14, but at zoom 15 I get no tiles, and the mentioned error. 

This is my code (API key hidden): 

var map = L.mapbox.map('map').setView([56.9, 24.5], 9);
L.TileLayer.multi({
    12: {
        url: 'http://tiles{s}.api.skobbler.net/tiles/{z}/{x}/{y}.png?api_key=xxxx',
        subdomains:'1234'
    },
    14: { 
        url: 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
    }
}, {
    minZoom: 0,
    maxZoom: 17,
    attribution: 'Tiles Courtesy of MapQuest — '
        + '© OpenStreetMap contributors, '
        + 'CC-BY-SA'
}).addTo(map);

**Comment by trakais** [comment]
OK, I got my mistake now. Didn't notice that the "14" in my example is between previous maxzoom and this. I changed it to 17 and now it works perfect. 

Issue invalid.

**Comment by mattiasb** [comment]
Btw, I think you don't need this plugin. Did you check out the jsfiddle here instead: http://jsfiddle.net/mattias_jcb/3hkYh/ ?

**Comment by trakais** [comment]
Thanks, didn't see the other method. I tried it, but it caused problems with Mapbox. It works with pure leaflet though, but causes some other problems, since my code relies on Mapbox code in some places.
