### ISSUE TITLE
Problem to see my TMS with Leaflet.Multilayer

### ISSUE THREAD

**Issue by abatany** [mattiasb/Leaflet.MultiTileLayer#2]
I want to test the plugin leaflet.multitilelayer for defining a TileLayer in terms of several TileServer urls. I have tested this plugin with data of others: it works (the example is here : http://makina-corpus.com/blog/metier/2013/infrastructure-webmapping-minimaliste-partie-3-leaflet). But when I have tested with our data (with server of spatial data GeoServer and MapServer to create TMS), it doesn't work. It seems that the coordinates of the tiles are not  good.

Here is our code :

 var PLAN  = 
  L.TileLayer.multi({
    17: { // this layer is shown at zoomlevels between maxZoom of 
          // previous layer and 17 (ie 17)
        url: 'http://xxx.XXX.XXX.XXX/geowebcache/service/tms/1.0.0/[our_data]/{z}/{x}/{y}.png',  
    },
     19: { // this layer is shown at zoomlevels between minZoom and 19 (ie 18,19)
        url: 'httpxxx.XXX.XXX.XXX/geowebcache/service/tms/1.0.0/[our_data]/{z}/{x}/{y}.png',
    } 
}, {
minZoom: 17,
maxZoom: 19,
});

The message that appaers for one tile is for example : 
### Coverage [minx,miny,maxx,maxy] is [238, 318, 273, 343, 9], index [x,y,z] is [255, 171, 9]

It seems thas our TMS are not well located with this command, because when I use the simple command L.tileLayer for these TMS, it works well.

Would anyone ever had this problem?
Have I missed something in the plugin?

Thank you for your help.

Aurélie

**Comment by mattiasb** [comment]
I have no idea. This code is really old. 

Did you try the code in the jsfiddle (http://jsfiddle.net/mattias_jcb/3hkYh/) instead?

**Comment by abatany** [comment]
This code works. 
I would like to give the ability for  users to decide to view or not view the layers on the map. This second code can't associate a name of a layer with several tilelayers url.
Is it possible to associate several tilelayers url (visible at different zoom level) at a name of a layer in the control layer with this plugin?

![image1](https://cloud.githubusercontent.com/assets/22076185/18380439/9f0864f0-7677-11e6-80a3-7a4e1eccef2b.jpg)

Thank you, 

Aurélie

**Comment by mattiasb** [comment]
I have no idea, sorry. Haven't worked with Leaflet in a while. You should direct this question at some general Leaflet forum I believe.
